version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  slack: circleci/slack@3.4.2
  
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
