CONTAINER VPpreviewsoftware
{
	NAME VPpreviewsoftware;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		BOOL VP_PREVIEWSOFTWARE_ENHANCEDOPENGL { ANIM OFF; }
		BOOL VP_PREVIEWSOFTWARE_TRANSPARENCY { ANIM OFF; }
		BOOL VP_PREVIEWSOFTWARE_SHADOW	{ ANIM OFF; }
		BOOL VP_PREVIEWSOFTWARE_POSTEFFECT { ANIM OFF; }
		BOOL VP_PREVIEWSOFTWARE_NOISE { ANIM OFF; }
		BOOL VP_PREVIEWSOFTWARE_REFLECTIONS { ANIM OFF; }
		LONG VP_PREVIEWSOFTWARE_ANTIALIASING	{ ANIM OFF; CYCLE { } }
	}
}
