var _strings = {
    STR_TITLE:                      { en: "Cinema 4D Multi-Pass" ,
                                  de: "Cinema 4D Multi-Pass" , 
                                  es:"Multi-Pase Cinema 4D" ,
                                  fr:"Multi-passes Cinema 4D" ,
                                  it:"Cinema 4D Multi-Pass"},  
    STR_HEADER:                     { en: "Select a Multi-Pass..." ,
                                  de: "Wählen Sie einen Multi-Pass...", 
                                  es:"Seleccionar un Multi-Pase...",
                                  fr:"Selectionner une Multi-Passe..." ,
                                  it:"Seleziona un Multi-Pass..."},  
    STR_PASSES_TIP:                 { en: "Select one or more layers..." ,
                                  de: "Wählen Sie einen oder mehrere Ebenen..." , 
                                  es:"Seleccionar una o más capas..." ,
                                  fr:"Sélectionner un ou plusieurs calques..." ,
                                  it:"Seleziona uno o pi livelli..."},  
    STR_PASS_RGBA:                  { en: "RGBA Image" ,
                                  de: "RGBA-Bild",  
                                  es:"Imagen RGBA" ,
                                  fr:"Image RGBA" ,
                                  it:"Immagine RGBA"},  
    STR_PASS_AMBIENT:               { en: "Ambient" ,
                                  de: "Umgebung",  
                                  es:"Entorno",
                                  fr:"Eclairage ambiant" ,
                                  it:"Ambiente"},  
    STR_PASS_DIFFUSE:               { en: "Diffuse" ,
                                  de: "Diffus",  
                                  es:"Difuso",
                                  fr:"Diffusion",
                                  it:"Diffuso"},  
    STR_PASS_SPECULAR:              { en: "Specular" ,
                                  de: "Glanzlicht",  
                                  es:"Especular",
                                  fr:"Spécularité",
                                  it:"Speculare"},  
    STR_PASS_SHADOW:                { en: "Shadow" ,
                                  de: "Schatten" , 
                                  es:"Sombra",
                                  fr:"Ombres",
                                  it:"Ombre"},  
    STR_PASS_REFLECTION:            { en: "Reflection" ,
                                  de: "Spiegelung",  
                                  es:"Reflexión",
                                  fr:"Réflexion",
                                  it:"Riflessioni"},  
    STR_PASS_REFRACTION:            { en: "Refraction" ,
                                  de: "Refraktion",  
                                  es:"Refracción",
                                  fr:"Réfraction" ,
                                  it:"Rifrazioni"},  
    STR_PASS_AMBIENTOCCLUSION:      { en: "Ambient Occlusion" ,
                                  de: "Ambient Occlusion",  
                                  es:"Oclusión Ambiental" ,
                                  fr:"Occlusion Ambiante",
                                  it:"Occlusione Ambientale"},  
    STR_PASS_GLOBALILLUMINATION:    { en: "Global Illumination" ,
                                  de: "Global Illumination",  
                                  es:"Iluminación Global" ,
                                  fr:"Illumination globale" ,
                                  it:"Illuminazione Globale"},  
    STR_PASS_CAUSTICS:              { en: "Caustics" ,
                                  de: "Caustics",  
                                  es:"Cáusticas",
                                  fr:"Caustiques",
                                  it:"Caustiche"},  
    STR_PASS_ATMOSPHERE:            { en: "Atmosphere" ,
                                  de: "Atmosphäre",  
                                  es:"Atmósfera",
                                  fr:"Atmosphère",
                                  it:"Atmosfera"},  
    STR_PASS_ATMUSPHERE_MULTIPLY:   { en: "Atmosphere (Multiply)" ,
                                  de: "Atmosphäre (Multipliziert)" , 
                                  es:"Atmósfera (Multiplicar)",
                                  fr:"Atmosphère (produit)",
                                  it:"Atmosfera (Multipla)"},  
    STR_PASS_POSTEFFECTS:           { en: "Post Effects" ,
                                  de: "Post-Effekte" , 
                                  es:"Post Efectos",
                                  fr:"Efets de post-production",
                                  it:"Post Effetti"},  
    STR_PASS_MAT_COLOR:             { en: "Material Color" ,
                                  de: "Material-Farbe",  
                                  es:"Material Color",
                                  fr:"Couleur des matériaux",
                                  it:"Colore Materiale"},  
    STR_PASS_MAT_DIFFUSION:         { en: "Material Diffusion" ,
                                  de: "Material-Diffusion",  
                                  es:"Material Difusión",
                                  fr:"Diffusion des matériaux",
                                  it:"Materiale Diffusione"},  
    STR_PASS_MAT_TRANSPARENCY:      { en: "Material Transparency" ,
                                  de: "Material-Transparenz",  
                                  es:"Material Transparencia" ,
                                  fr:"Transparence des matériaux",
                                  it:"Materiale Trasparenza"},  
    STR_PASS_MAT_REFLECTION:        { en: "Material Reflection" ,
                                  de: "Material-Spiegelung" ,
                                  es:"Material Reflexión",
                                  fr:"Réflexion des matériaux",
                                  it:"Materiale Riflessione"},  
    STR_PASS_MAT_ENVIRONMENT:       { en: "Material Environment" ,
                                  de: "Material-Umgebung" , 
                                  es:"Material Entorno",
                                  fr:"Environnement des matériaux",
                                  it:"Materiale Ambiente"},  
    STR_PASS_MAT_SPECULAR:          { en: "Material Specular" ,
                                  de: "Material-Glanzlicht" , 
                                  es:"Material Especular" ,
                                  fr:"Specularité des matériaux",
                                  it:"Materiale Speculare"},  
    STR_PASS_MAT_SPECULARCOLOR:     { en: "Material Specular Color" ,
                                  de: "Material-Glanzfarbe",  
                                  es:"Material Color Especular",
                                  fr:"Couleur spéculaire des matériaux",
                                  it:"Materiale Colore Speculare"},  
    STR_PASS_MAT_NORMAL:            { en: "Material Normal" ,
                                  de: "Material-Normale" , 
                                  es:"Material Normales",
                                  fr:"Normale de matériau",
                                  it:"Materiale Normale"},  
    STR_PASS_MAT_UVW:               { en: "Material UVW" ,
                                  de: "Material-UVW" , 
                                  es:"Material UVW",
                                  fr:"UVW de matériau",
                                  it:"Materiale UVW"},  
    STR_PASS_MAT_MOTIONVECTOR:      { en: "Motion Vector" ,
                                  de: "Motion-Vektor" , 
                                  es:"Vector de Movimiento" ,
                                  fr:"vecteur de mouvement",
                                  it:"Motion Vector"},  
    STR_PASS_MAT_ILLUMINATION:      { en: "Illumination" ,
                                  de: "Illumination",  
                                  es:"Iluminación",
                                  fr:"Illumination",
                                  it:"Illuminazione"
                                  },  
    STR_PASS_DEPTH:                 { en: "Depth" ,
                                  de: "Tiefe",  
                                  es:"Profundidad" ,
                                  fr:"Profondeur",
                                  it:"Profonditˆ"},  
    BTN_OK:                         { en: "OK" ,
                                  de: "OK",  
                                  es:"OK",
                                  fr:"OK",
                                  it:"OK"},   
    BTN_CANCEL:                     { en: "Cancel",
                                  de: "Abbrechen",  
                                  es:"Cancelar",
                                  fr:"Annuler",
                                  it:"Cancella"}
};
