var _strings = {
    STR_TITLE:          { en: "About CINEWARE" ,
                                  de: "Über CINEWARE" , 
                                  es:"Acera de CINEWARE",
                                  fr:"CINEWARE A propos",
                                  it:"Su CINEWARE"}, 
    
    BTN_CLOSE:          { en: "Close" ,
                                    de:"Schließen" , 
                                  es:"Cerrar",
                                  fr:"Fermer",
                                  it:"Chiudi"},  
                                    
    STR_VERSION:        { en: "CINEWARE -  Version %1.%2.%3  © MAXON"  ,
                                    de:"CINEWARE -  Version %1.%2.%3 © MAXON" , 
                                  es:"CINEWARE - Versión %1.%2.%3 © MAXON",
                                  fr:"CINEWARE -  Version %1.%2.%3 © MAXON",
                                  it:"CINEWARE - Versione %1.%2.%3 © MAXON"}, 
    STR_ONLINE:         { en: "Visit us online: www.maxon.net/cineware_ae"  ,
                                    de:"Besuchen Sie: www.maxon.net/cineware_ae"  , 
                                  es:"Visítenos online: www.maxon.net/cineware_ae",
                                  fr:"Rendez-nous visite en ligne : www.maxon.net/cineware_ae",
                                  it:"Visitaci on online su: www.maxon.net/cineware_ae"}, 
    STR_ABOUTTXT:       { en:"""MAXON CINEWARE is part of the MAXON product family and your direct link from Adobe AfterEffects to MAXON Cinema 4D, our industry-leading, 3D motion graphics tool kit known for its seamless connectivity to popular 2D motion graphics and compositing tools. Artists and designers around the world rely on this professional 3D software package as the first choice for the creation of high-end 3D images and animations for film, broadcast, architecture, games, multimedia, design and engineering. MAXON Cinema 4D is renowned for offering spectacular image quality and an intuitive, easy-to-use interface that puts professional results within reach of artists at all levels of CGI experience.

Headquartered in Friedrichsdorf, Germany, MAXON Computer is a developer of professional 3D modeling, painting, animation and rendering solutions. Its award-winning Cinema 4D and BodyPaint 3D software products have been used extensively to help create everything from stunning visual effects in top feature films, TV shows and commercials, cutting-edge game cinematics for AAA games, as well for medical illustration, architectural and industrial design applications. MAXON has offices in Germany, USA, United Kingdom, France, Japan and Singapore. MAXON products are available directly from the website and its worldwide distribution channel. Specially priced learning editions of the company software solutions are also made available to educational institutions.
""",
                                de: """MAXON CINEWARE ist Teil der MAXON-Produktfamilie. Cinema 4D ist ein führendes 3D-Motion-Graphics-Werkzeug, das für seine nahtlose Anbindung an gängige und bekannte 2D-Motion-Graphics- und Kompositions-Programme bekannt ist. Künstler und Designer rund um die Welt vertrauen auf Cinema 4D, der ersten Wahl, wenn es darum geht, hochwertige 3D-Bilder und -Animationen für Film, Fernsehen, Architektur, Spiele, Multimedia, Design und Konstruktion zu erstellen. Cinema 4D ist berühmt für seine hochwertige Bildqualität und die intuitive, leicht zu bedienende Benutzeroberfläche, die Künstlern jeder Erfahrung mit Computergrafik zu schnellen und professionellen Ergebnissen verhilft.

MAXON Computer ist ein führender Entwickler von professionellen 3D-Modelling, Painting, Animations- und Rendering-Lösungen. Die vielfach ausgezeichneten Softwarepakete Cinema 4D und BodyPaint 3D werden weltweit in zahlreichen Produktionen aus den Bereichen Film, Fernsehen, Werbung, Spielen, sowie Visualisierung von Architektur, Medizin, Produktdesign oder Infografik eingesetzt. Das in Friedrichsdorf bei Frankfurt/M. beheimatete Unternehmen unterhält Niederlassungen und Repräsentanzen in den USA, dem Vereinigten Königreich, Frankreich, Japan und Singapur. MAXON-Produkte sind direkt bei MAXON oder den zertifizierten Fachhandelspartnern erhältlich. Für Ausbildungsinstitutionen sind Studentenversionen der Firmen-Software-Lösungen erhältlich.
    """,  
                                  es : """MAXON CINEWARE forma parte del grupo de productos MAXON. Cinema 4D es líder en herramientas de motion graphics 3D reconocido por su conectividad sin fisuras con las más populares herramientas de motion graphics 2D y composición. Los artistas y diseñadores de todo el mundo confían en este paquete de software 3D profesional, como la primera opción para crear imágenes 3D de gama alta y animaciones para cine, broadcast, arquitectura, juegos, multimedia, diseño e ingeniería. Cinema 4D es conocido por ofrecer una calidad de imagen espectacular y una interfaz intuitiva y fácil de usar, aportando resultados profesionales al alcance de los artistas con experiencia CGI de cualquier nivel.
Con sede en Friedrichsdorf, Alemania, MAXON Computer es un desarrollador de soluciones profesionales de modelado 3D, painting, animación y renderizado. Sus galardonados productos de software Cinema 4D y BodyPaint 3D se han utilizado ampliamente para ayudar a crear de todo, desde impresionantes efectos visuales en grandes películas, programas de televisión y anuncios publicitarios, juegos cinemáticos de vanguardia para juegos AAA, así como para la ilustración médica, arquitectónica y diseño industrial. MAXON tiene oficinas en Alemania, EE.UU., Reino Unido, Francia, Japón y Singapur. Los productos de MAXON están disponibles directamente desde su web y desde su canal de distribución en todo el mundo. Para las instituciones educativas están también a su disposición ediciones educativas del software de la compañía, con precios especiales.
    """,
                                  fr:"""MAXON CINEWARE est le produit de motion graphics 3D leader dans son domaine. Il est notoirement célèbre grâce à sa connectivité avec de nombreux outils de motion graphics et compositing 2D standards.  Les artistes et designeurs du monde entier font confiance à ce logiciel 3D professionnel en le sélectionnant come outil de prédilection pour créer des images et animations 3D haut de gamme pour le cinéma, la télévision, l'architecture, les jeux, le multimédia, le design et l'ingénierie. Cinema 4D est renommé pour offrir non suelemnt une qualité d'image spectaculaire mais également une interface utilisateur à la fois intuitive et simple d'emploi, apte à garantir des résultats professionnels quelque soit le niveau d'expérience et de pratique des images de synthèse des infographistes l'utilisant.

Basé en Allemagne, MAXON Computer est le développeur de solutions leader dans l'industrie pour la modélisation, le texturage, l'animation et le rendu pour la 3D professionnelle. Ses logiciels Cinema 4D et BodyPaint 3D, vainqueurs de plusieurs prix, ont été utilisés pour créer des effets spéciaux éblouissants dans des films, des émissions de télévision et dans des publicités, mais aussi pour créer des cinématiques haut-de-gamme pour les jeux AAA, pour les illustrations médicales, ainsi que pour des applications de design architectural et industriel. MAXON possède des bureaux en Allemagne, aux États-Unis, au Royaume-Uni, au France, en Japon et au Singapour. Les produits MAXON sont disponibles directement chez MAXON ainsi qu'auprès de son réseau de distribution et de revente mondial. Des versions Education des solutions logicielles de la société sont également proposées à des établissemnts scolaires.
    """,
                                  it: """MAXON CINEWARE  parte integrante della famiglia dei prodotti MAXON. Cinema 4D Ã¨ un leader nel settore degli strumenti dedicati alla motion-graphic 3D, rinomato per l'illimitata connettivitÃ  verso i maggiori strumenti per la motion-graphic 2D e il compositing. Artisti e designer in tutto il mondo si affidano a questo software 3D professionale per la creazione di immagini e animazioni 3D di alta qualitÃ  per film, broadcast, architettura, videogiochi, multimedia, design e progettazione. Cinema 4D Ã¨ riconosciuto per la sua spettacolare qualitÃ  d'immagine e per l'interfaccia intuitiva e facile da usare, che permette ad artisti di ogni livello di esperienza in CG di raggiungere risultati professionali.

Con sede a Friedrichsdorf, in Germania, MAXON Computer sviluppa soluzioni per la modellazione, il painting, l'animazione ed il rendering 3D professionale. I suoi pluripremiati prodotti software, Cinema 4D e BodyPaint 3D, sono stati ampiamenti utilizzati in ogni tipologia di progetto, dagli effetti speciali nei film, ai programmi televisivi, da spot pubblicitari all'avanguardia a filmati per videogiochi AAA, da illustrazioni mediche ad applicazioni nella progettazione architettonica ed industriale. MAXON ha uffici in Germania, negli USA, nel Regno Unito, in Francia in Giappone e a Singapore. I prodotti MAXON sono disponibili presso MAXON e presso la sua rete mondiale di distributori. Sono inoltre disponibili soluzioni del software a prezzo speciale dedicate agli Istituti di Istruzione.
    """}
};
