CONTAINER fobjimport2
{
	NAME		fobjimport2;
	INCLUDE Fbase;

	GROUP OBJIMPORTOPTIONS_GROUP
	{
		SEPARATOR OBJIMPORTOPTIONS_GROUP_PRESETS { }

		LONG OBJIMPORTOPTIONS_PRESETS
		{
			CYCLE { }			
		}

		GROUP
		{
			COLUMNS 2;
			BUTTON OBJIMPORTOPTIONS_PRESETS_CUSTOM_SAVEBUTTON {}
			BUTTON OBJIMPORTOPTIONS_PRESETS_CUSTOM_DELETEBUTTON {}
		}
		
		SEPARATOR OBJIMPORTOPTIONS_GROUP_GENERAL { }

		UNITSCALE OBJIMPORTOPTIONS_SCALE { }
		LONG			OBJIMPORTOPTIONS_NORMALS
		{
			CYCLE
			{
				OBJIMPORTOPTIONS_NORMALS_NOIMPORT;
				OBJIMPORTOPTIONS_NORMALS_PHONGTAG;				
				OBJIMPORTOPTIONS_NORMALS_VERTEX;
			}			
		}

		REAL OBJIMPORTOPTIONS_PHONG_ANGLE_DEFAULT { }

		BOOL OBJIMPORTOPTIONS_TEXTURECOORDINATES { }

		LONG OBJIMPORTOPTIONS_SPLITBY
		{
			CYCLE
			{
				OBJIMPORTOPTIONS_SPLITBY_ONEOBJECT;
				OBJIMPORTOPTIONS_SPLITBY_OBJECT;
				OBJIMPORTOPTIONS_SPLITBY_GROUP;				
				OBJIMPORTOPTIONS_SPLITBY_MATERIAL;
				OBJIMPORTOPTIONS_SPLITBY_GROUP_COMBINE_NAME_COLLISIONS;
			}
		}

		SEPARATOR OBJIMPORTOPTIONS_GROUP_MATERIAL { }

		LONG OBJIMPORTOPTIONS_MATERIAL
		{
			CYCLE
			{
				OBJIMPORTOPTIONS_MATERIAL_NONE;
				OBJIMPORTOPTIONS_MATERIAL_DEFAULTPEROBJECT;
				OBJIMPORTOPTIONS_MATERIAL_MTLFILE;
				OBJIMPORTOPTIONS_MATERIAL_DEFAULTPERMTLFILE;
			}
		}


		LONG OBJIMPORTOPTIONS_DEFAULTMATERIAL
		{
			CYCLE
			{
				OBJIMPORTOPTIONS_DEFAULTMATERIAL_WHITE;
				OBJIMPORTOPTIONS_DEFAULTMATERIAL_RANDOMCOLORS;
			}
		}

		LONG OBJIMPORTOPTIONS_MATERIAL_MIXMODE
		{
			CYCLE
			{
				OBJIMPORTOPTIONS_MATERIAL_MIXMODE_BLEND;
				OBJIMPORTOPTIONS_MATERIAL_MIXMODE_ADD;
				OBJIMPORTOPTIONS_MATERIAL_MIXMODE_SUB;
				OBJIMPORTOPTIONS_MATERIAL_MIXMODE_MUL;
			}
		}

		BOOL OBJIMPORTOPTIONS_INVERT_TRANSPARENCY { }

		SEPARATOR OBJIMPORTOPTIONS_GROUP_OPTIONAL { }
		
		GROUP
		{
			COLUMNS 2;
			BOOL OBJIMPORTOPTIONS_POINTTRANSFORM_FLIPX { }
			BOOL OBJIMPORTOPTIONS_POINTTRANSFORM_SWAPXY { }
			BOOL OBJIMPORTOPTIONS_POINTTRANSFORM_FLIPY { }
			BOOL OBJIMPORTOPTIONS_POINTTRANSFORM_SWAPXZ { }
			BOOL OBJIMPORTOPTIONS_POINTTRANSFORM_FLIPZ { }
			BOOL OBJIMPORTOPTIONS_POINTTRANSFORM_SWAPYZ { }
		}

		GROUP
		{
			COLUMNS 2;
			BOOL OBJIMPORTOPTIONS_FLIPFACES { }
			BOOL OBJIMPORTOPTIONS_FLIPUVW   { }
		}

		LONG OBJIMPORTOPTIONS_LINES
		{
			CYCLE
			{
				OBJIMPORTOPTIONS_LINES_DEFAULT;
				OBJIMPORTOPTIONS_LINES_CLOSED;
				OBJIMPORTOPTIONS_LINES_ASPOLYS;
			}
		}

		// Taken out of R17 SP1 HF because UI change was rejected and other changes were accepted
		// BOOL OBJIMPORTOPTIONS_OPTIMIZE_VERTICES { }
		BOOL OBJIMPORTOPTIONS_REPORT_SCRIPTCONSOLE { }
	}
}
